### ISSUE TITLE
[Feature Request] Support SparkFun RV-8803

### ISSUE THREAD

**Issue by BiatuAutMiahn** [mcauser/micropython-tinyrtc-i2c#1]
Can you support the SparkFun RV-8803?

Product Page: https://www.sparkfun.com/products/16281

Thank you

**Comment by mcauser** [comment]
This library is for the DS1307 RTC. The SparkFun RTC is a completely different chip.
There is an Arduino library you could use: https://github.com/sparkfun/SparkFun_RV-8803_Arduino_Library
